version: '3.8'

services:
  app:
    build: .
    container_name: cloud-hub-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - UPLOAD_PATH=/app/data/uploads
    volumes:
      - ./data/uploads:/app/data/uploads
      - ./data/backups:/app/data/backups
      - ./docs:/app/docs
    networks:
      - cloud-hub-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/api/dashboard/stats"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  cloud-hub-network:
    driver: bridge

volumes:
  uploads_data:
  backups_data:
